package softSkills;

public class Feb_5_20 {
 /*   02/06/2020
    Interview questions :
            1.Can you describe me your scrum?
            2.What is the difference between test case and test Scenario?
            3.What is test plan ? who's responsible for create test plan in your team?
            ==============================================
    STLC :
    Requirement analysis-> test plan -> test case-> ? Environment set up -->
    Environemnt set up : two main thing: 1, which environemnt we need to testing of those user stories. 2. environment is up and running.
    IN SPRINT , user stories after tested in  TEST EVN -> staging Env
    test environment --> multiple
    example : amazon production env: www.amazon.com
    amazon test evn: www.amazon-qa1.com
    what if your test case is failed?
    COME BACK AT  8: 00 PM
=================================================
    interview questions :
            1.How do you handle if you found a bug?
            2.What tool are you using for bug report?
            3.What do you do if the defect/bug is rejected by developers?
            4.What do you do if the defect/bug is not reproducible?
            5.How do you report the bug? what feilds you need to enter?
            new -> reproduce bug coule times-> assigned to developers -> open -> valid -> fixed -> assing back to testes -> rhe bug? what fields you need to enter on bug report?
    etesting -> closed or reopen
    purpose :
    regression : make sure that all existing and new functionalities working as expected.
    Re testing : only foucs on specific funtionality and make sure that bug is fixed.
    reproducible--> repeat your steps find a same bug
    non -reproducible -> run time error
    ex: session time out
    login functionality :
    scenario : user should not access with invalid password
    scenario : user should not able to access with out entering password feild.
            steps for reproduce:
            1. as user open url : www.amazon.qa1.com
2. enter valid user name as user 123@gmail.com
3. enter invalid password as abvcg123#
    Expected resutl: system should not allow user to login with invalid user credential.
    Actual resutl: user was able to login with invalid credential
    Test environment : www.amazon.qa1.com
    Test data: user name : 123@gmail.com
    invalid password: abvcg123#
    Note: however, while I'm testing below scenrio it passed.
    user should not able to access with out entering password feild.
===============================================
    summary :
            1.You need to know STLC process, able to answer it
2. what is test plan doc? who is responsible for write test plan document ?
            3. how to create test case.
            4. difference between test case and test scenario
5.bug life cycle ?
            6.What do you do if the defect/bug is rejected by developers?
            7.What do you do if the defect/bug is not reproducible?
            8. submit STLC quiz before next thursday class.
            =============================================
    interview question :
            1.What are the issue types that are created and tracked via JIRA?
            2.How you open a bug on JIRA?
            3.Can you list the report types generated by JIRA?
            4.Can you mention a way with which issue can be shared with other users in JIRA?
            5.What is the importance of linked in JIRA?
            6.What are the most useful JIRA add-ons?


  */
}
